const CONFIG = window.ZVAKHO_CONFIG;
const $ = (s,r=document)=>r.querySelector(s);
const money = n => `$${Number(n||0).toFixed(2)}`;
function api(path){ return `${CONFIG.apiBase}${path}`; }
function norm(s){ return String(s||'').toLowerCase(); }
function isPaid(o){ return ['paid','confirmed','complete','completed'].includes(norm(o.payment_status||o.paynow_status||o.status)); }
function isPending(o){ return ['pending','created','processing'].includes(norm(o.payment_status||o.paynow_status||o.status)); }
function amount(o){ return Number(o.amount ?? o.total_amount ?? o.order_total ?? o.price ?? 0); }
function orderDate(o){ return o.paid_at || o.created_at || o.updated_at || ''; }
function artistById(id){ return CONFIG.artists.find(a=>a.id===id || a.slug===norm(id)); }
function artistByHost(){ const host = location.hostname.split('.')[0].toLowerCase(); const params=new URLSearchParams(location.search); const q = (params.get('artist')||params.get('artist_id')||'').toLowerCase(); return CONFIG.artists.find(a=>a.slug===host||a.slug===q||a.id.toLowerCase()===q) || CONFIG.artists[0]; }
async function fetchJSON(url){ try{ const r=await fetch(url,{cache:'no-store'}); if(!r.ok) throw new Error(r.status); return await r.json(); } catch(e){ return null; } }
function uniq(arr){ return [...new Set(arr.filter(Boolean))]; }
function sinceDays(o,days){ const d=new Date(orderDate(o)); return !isNaN(d) && (Date.now()-d.getTime()) <= days*86400000; }
function today(o){ const d=new Date(orderDate(o)); return !isNaN(d) && d.toDateString()===new Date().toDateString(); }
function leaderboard(orders, keyFn, limit=5){ const map = new Map(); orders.forEach(o=>{ const k=keyFn(o)||'Unspecified'; const row=map.get(k)||{name:k,total:0,count:0}; row.total+=amount(o); row.count++; map.set(k,row); }); return [...map.values()].sort((a,b)=>b.total-a.total).slice(0,limit); }
function renderList(el, rows, empty='No confirmed data yet.'){ if(!el) return; el.innerHTML = rows.length ? rows.map(r=>`<div class="list-row"><span>${r.name}</span><strong>${money(r.total)} · ${r.count}</strong></div>`).join('') : `<div class="empty">${empty}</div>`; }
function renderArtists(){ const el=$("#artistsGrid"); if(!el) return; el.innerHTML = CONFIG.artists.map(a=>`<article class="artist-card"><img src="${a.image}" alt="${a.name}"><div class="pad"><div class="eyebrow">Active artist</div><h3>${a.name}</h3><p>${a.positioning}</p><a class="btn" href="/store/?artist=${a.slug}">Open official store</a></div></article>`).join(''); }
async function renderStore(){ const root=$("#tracks"); if(!root) return; const a=artistByHost(); document.title=`${a.name} — Official ZVAKHO Store`; const hero=$("#storeHero"); if(hero) hero.style.backgroundImage=`url('${a.header}')`; $("#artistName").textContent=a.name; $("#artistSub").textContent=`Official ZVAKHO store for direct tracks, albums, and selected release campaigns. Payments are completed through WhatsApp and confirmed before delivery.`; $("#artistWa").href=a.wa; $("#artistWa").textContent=`Enter ${a.name} sales funnel`; root.innerHTML='<div class="empty">Loading official catalogue…</div>'; const data = await fetchJSON(api(`/artist-products?artist_id=${encodeURIComponent(a.id)}`)); const products = Array.isArray(data) ? data : (data?.products||[]); const live = products.filter(p => norm(p.status||'active') === 'active' && ['music','track','album','release'].includes(norm(p.product_type||p.type||'music'))); if(!live.length){ root.innerHTML = `<div class="empty"><strong style="color:var(--ink)">Official catalogue opens in WhatsApp.</strong><br>No public product list is displayed until the live catalogue is connected. Use the button above to enter the artist’s active ZVAKHO sales funnel.</div>`; return; } root.innerHTML = live.map(p=>{ const type=String(p.product_type||p.type||'music'); const price = p.price ?? p.amount; const priceText = price ? money(price) : 'Price shown in WhatsApp'; return `<div class="track"><div><strong>${p.product_name||p.title||'Music release'}</strong><br><span style="color:var(--muted)">${type.charAt(0).toUpperCase()+type.slice(1)} · Delivery after confirmed payment</span></div><div class="price">${priceText}</div><a class="btn primary" href="${a.wa}">Purchase via WhatsApp</a></div>`; }).join(''); }
async function renderDashboard(mode){ const body=$("#ordersBody"); if(!body) return; const refresh=$("#refreshBtn"); const artist = mode==='artist' ? artistByHost() : null; if(mode==='artist' && $("#dashArtistName")) $("#dashArtistName").textContent=`${artist.name} revenue dashboard`; async function load(){ body.innerHTML='<tr><td colspan="7">Loading platform data…</td></tr>'; const endpoint = mode==='artist' ? `/artist-dashboard?artist_id=${artist.id}` : '/owner-dashboard'; let data = await fetchJSON(api(endpoint)); if(!data) data = await fetchJSON(api(mode==='artist' ? `/dashboard/artist?artist_id=${artist.id}` : '/dashboard/admin')); const all = data?.orders || data?.transactions || []; const paid = all.filter(isPaid); const pending = all.filter(isPending); const revenue = data?.summary?.total_revenue ?? paid.reduce((s,o)=>s+amount(o),0); const totalOrders = mode==='admin' ? all.length : paid.length; const customers = uniq(paid.map(o=>o.customer_phone||o.phone||o.customer_email||o.email)).length; const todayRevenue = paid.filter(today).reduce((s,o)=>s+amount(o),0); const sevenRevenue = paid.filter(o=>sinceDays(o,7)).reduce((s,o)=>s+amount(o),0); if($("#mRevenue")) $("#mRevenue").textContent=money(revenue); if($("#mOrders")) $("#mOrders").textContent=totalOrders; if($("#mArtists")) $("#mArtists").textContent=mode==='artist' ? '1' : (data?.summary?.active_artists || uniq(all.map(o=>o.artist_id)).length || CONFIG.artists.length); if($("#mCustomers")) $("#mCustomers").textContent=customers; if($("#mToday")) $("#mToday").textContent=money(todayRevenue); if($("#mSeven")) $("#mSeven").textContent=money(sevenRevenue); if($("#mPending")) $("#mPending").textContent=pending.length; if($("#mUpdated")) $("#mUpdated").textContent=new Date().toLocaleTimeString(); const productRows = leaderboard(paid, o=>o.product_name||o.order_product||o.title); renderList($("#productLeaderboard"), productRows, 'No product performance available yet.'); renderList($("#artistLeaderboard"), leaderboard(paid, o=>artistById(o.artist_id)?.name || o.artist_id), 'No artist revenue available yet.'); if($("#mBest")) $("#mBest").textContent = productRows[0]?.name || '—'; if(!paid.length && !pending.length){ body.innerHTML=`<tr><td colspan="7" class="empty">No platform transactions returned yet. This interface does not create sample orders or artificial revenue.</td></tr>`; return; } const rows = (mode==='admin' ? all : paid).slice(0,50); body.innerHTML=rows.map(o=>`<tr><td>${orderDate(o)}</td><td>${artistById(o.artist_id)?.name || o.artist_id || ''}</td><td>${o.product_name||o.order_product||o.title||''}</td><td>${money(amount(o))}</td><td>${o.customer_phone||o.phone||o.customer_email||''}</td><td>${o.payment_status||o.paynow_status||o.status||''}</td><td>${o.payment_reference||o.transaction_reference||o.reference||''}</td></tr>`).join(''); }
refresh?.addEventListener('click', load); load(); setInterval(load, CONFIG.refreshMs || 20000); }
renderArtists(); renderStore(); if(document.body.dataset.dashboard) renderDashboard(document.body.dataset.dashboard);